audit_header: false
title: "Long Beach's Best Real Estate Training"
description: Scott Kato, a top Real Estate Agent in Long Beach, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: http://scottkato.eventbrite.com/
  - title: Free Strategy Call
    url: /contact/
client:
  name: Scott Kato
  title:
  license_number:
  about_markdown: |
    We are a team of real estate pros with diverse backgrounds, which allows us to think differently than other real estate groups. We are dedicated to providing the highest quality of service to everyone from first-time home buyers to experienced real estate investors. Clients continue to work with us and refer their friends and family because of our dedication to customer service, results, and love for the communities we serve. Interested in what we do and how we do it? Let's chat today!
  market: Long Beach
  brand: Kato Group Real Estate
  brokerage: Keller Williams
  address: 2883 E. Spring Street, Ste. 100 Long Beach, CA 90806
  phone: 562-716-4767
  phone_type:
  phone2:
  phone2_type:
  email: skato@kw.com
  url: http://www.katogroup.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how -- CLIENT BRAND -- can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: true
  facebook_url: https://www.facebook.com/KatoGroup/
  linkedin_url:
  youtube_url: https://www.youtube.com/kwpevideos
  twitter_url: https://twitter.com/scottkato
  instagram_url: http://instagram.com/kwpacificestates
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/ScottKato/
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Long Beach Real Estate Podcast with Scott Kato'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Long Beach Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional Long Beach Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Long Beach, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Scott Kato'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Long Beach Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#ff4c29'
  accent_color: '#f7be2f'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
